version: "2.4"
services:
   main:
      image: cs598p1-main
      hostname: main
      tty: true
      stdin_open: true
      environment:
         - NODE_ID=main
      ports:
        - 8080:8080
        - 8081:8081
      command: ["/bin/bash", "start-main.sh"]
   worker1:
      image: cs598p1-worker
      hostname: worker1
      tty: true
      stdin_open: true
      environment:
         - NODE_ID=worker1
      command: ["/bin/bash", "start-worker.sh"]
   worker2:
      image: cs598p1-worker
      hostname: worker2
      tty: true
      stdin_open: true
      environment:
         - NODE_ID=worker2
      command: ["/bin/bash", "start-worker.sh"]
